[package]
name = "sqruff"
description = "A high-speed SQL linter."
version = "0.1.3"
edition = "2021"
license = "MIT"

[[test]]
name = "ui"
harness = false

[dependencies]
sqruff-lib = "0.1.3"
clap = { version = "4", features = ["derive"] }
glob = "0.3.1"

[dev-dependencies]
ui_test = "0.22"
